version: 2

defaults: &defaults
  branches:
    ignore:
      - gh-pages
  docker:
    - image: circleci/node:12
  working_directory: ~/blog

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

  flow-typed:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - flow-typed-{{ checksum "package-lock.json" }}
      - run: npm run flow-typed
      - save_cache:
          paths:
            - flow-typed
          key: flow-typed-{{ checksum "package-lock.json" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test --runInBand --no-cache

  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test:coverage --runInBand --no-cache
      - save_cache:
          key: coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - coverage

  deploy:
    branches:
      only:
        - master
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - install
      - flow-typed:
          requires:
            - install
      - test:
          requires:
            - install
      - coverage:
          requires:
            - install
      - deploy:
          requires:
            - install